### ISSUE TITLE
runServerPartT doc mentions runWebT, which is not exported

### ISSUE THREAD

**Issue by ddssff** [Happstack/happstack-server#87] opened 2024-07-20 11:53 UTC
```
-- | Particularly useful when combined with 'runWebT' to produce
-- a @m ('Maybe' 'Response')@ from a 'Request'.
runServerPartT :: ServerPartT m a -> Request -> WebT m a
runServerPartT = runReaderT . unServerPartT
```

**Comment by ysangkok** [comment] 2024-07-21 20:35
This seems like a duplicate of #68

**Comment by stepcut** [comment] 2024-08-05 18:45
exported in 7.9.2.

**Closed** 2024-08-05 18:45 UTC
